#!/bin/zsh
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus

function gpaste_run() {
    if [[ -x $(which gpaste-client) ]]; then
        echo $(which gpaste-client) --oneline
    elif [[ -x $(which gpaste) ]]; then
        echo $(which gpaste) -client --oneline
    else
        echo There is no gpaste in \$PATH>/dev/stderr
        exit 1
    fi
}

function clip_main(){
    local rofi_pid=" -pid /run/user/$(id -u)/rofi_clip.pid"
    declare -a rofi_opts_
    local x11_width="$(xrandr -q |awk '/Screen/{print $8}')"
    local width_=$[x11_width-70]
    local lines_=10
    local yoffset_=-22
    readonly rofi_cmd=(
        rofi -dmenu 
        -opacity "${opacity_}"
        -theme-str "'#window { width:${width_}; y-offset: ${yoffset_}; location: south; anchor: south; }'"
        -theme-str "'#listview { lines:${lines_}; }'"
        "${rofi_pid}" -i -levenshtein-sort -matching glob -dmenu -p '"[>>]"'
    )
    local menu=$($(gpaste_run)|eval ${rofi_cmd})
    local selection=$(echo "${menu}" | cut -d ':' -f1)
    $(gpaste_run) select ${selection}
}

case "$1" in
    *) clip_main
esac
