#!/bin/zsh
local snapshot_name="${dir_}/snapshot_$$.png"

function msg(){
    notify-send "$@"
}

function webcam_record(){
    local dir_="${HOME}/tmp/shots"

    local rec_name="${dir_}/rec-$(date +%y%m%d_%H%M)_$$.avi"
    local adev="hw.0,0"
    local webcam_record_pid="${dir_}/webcam_record$$.pid"

    local w_=1280 h_=720

    ffmpeg -f video4linux2 -i "${i}" -f image2 "${snapshot_name}" 2>/dev/null
    mencoder tv:// -tv driver=v4l2:width="${w_}":height="${h_}":device="${i}":alsa:forceaudio:amode=0:adevice="${adev}" \
        -ovc lavc -lavcopts vcodec=mpeg4 -oac mp3lame -lameopts vbr=3:br=32:mode=3 -af volnorm \
        -o "${rec_name}" &>/dev/null&
    echo $! >> "${webcam_record_pid}"
    if [[ -f "${webcam_record_pid}"  ]]; then
        kill $(< "${webcam_record_pid}") && rm "${webcam_record_pid}"
    else
        webcam_record
    fi
}

case $1 in
    "")
        for webcam in /dev/video[0-9]*;
            mpv --fullscreen=no --x11-name="webcam" --title="webcam" "av://v4l2:${webcam}"
        ;;
    s*)
        for webcam in /dev/video[0-9]*;
            ffmpeg -f video4linux2 -i ${webcam} -f image2 "${snapshot_name}" 2>/dev/null || \
                msg "Cannot to take screenshot: You are using webcam now :("
        ;;
    r*)
        for webcam in /dev/video[0-9]*;
            webcam_record "$@"
        ;;
esac
