#!/bin/zsh

main(){
    case "$1" in
        c*) 
            shift
            # Transmission-related stuff
            inotifywait -m -q -e close --format "%f" ${XDG_DOWNLOAD_DIR}/ \
            | while IFS= read -r file_; do
                file=$(readlink -f ${XDG_DOWNLOAD_DIR}/${file_})
                if [[ "${file}" =~ ".torrent.added"$ ]]; then
                    mv "${file}" "$(readlink -f ${HOME}/tmp/)"
                    send_notify
                fi
            done
        ;;
        s*)
            shift

            local dw="$(readlink -f ${HOME}/dw/)"
            local doc="$(readlink -f ${HOME}/doc/new/)"
            local vid="$(readlink -f ${HOME}/vid/new/)"

            rmdir ${dw}/{img,archive} 2> /dev/null&
            mkdir ${dw}/{img,archive}

            find ${dw}/ -maxdepth 1 -name "*.iso" \
                -exec mv -n -t ${dw}/img {} +
            find ${dw}/ -maxdepth 1 -regextype posix-egrep -regex \
                ".*\.(zip|7z|rar|gz|xz|bz2|tgz|tar.*)$" -exec mv -vnt ${dw}/archive {} +
            find ${dw}/ -maxdepth 1 -regextype posix-egrep -regex \
                ".*\.(pdf|ps|djvu|txt|doc|docx|fb2|epub|rtf)$" -exec mv -vnt ${doc}/ {} +
            find ${dw}/ -maxdepth 1 -regextype posix-egrep -regex \
                ".*\.(flv|mp4|avi|mkv|mov|webm|wmv)$" -exec mv -vnt ${vid}/ {} +
            find ${dw}/ -maxdepth 1 -regextype posix-egrep -regex \
                ".*\.(mp3|ogg|flac|wma|flac|alac|dsf|dsd)$" -exec mv -vnt ${dw}/aud {} +

            rmdir ${dw}/{img,archive} 2> /dev/null&
        ;;
    esac
}

hi(){
    local msg="$(xrq color$1)"
    builtin print "<span weight='bold' color='${msg}'>"
}

st=$(hi 4)
cl="</span>"
bold="<span weight='bold'>"

wf(){
    builtin print "${st}⟬${cl}${bold}$1${cl}${st}⟭${cl}"
}

send_notify(){ 
    notify-send -h "string:fgcolor:$(xrq foreground)" "$(wf "mv")$(wf "${file}")->$(wf ${HOME}/tmp)"
}

main "$@"
