#!/bin/zsh

linux=linux
esp=/boot

function cmdline(){
    # kexec -l /boot/efi/vmlinuz-linux --initrd=/boot/efi/initramfs-linux.img --command-line=initrd=\intel-ucode.img initrd=\initramfs-linux.img root=PARTUUID=c12f9faf-d0d7-41df-b7da-49a2fd4a8519 init=/usr/bin/init rw rootflags=rw vga=current rd.systemd.show_status=auto rd.udev.log-priority=3 libahci.ignore_sss=1
    awk -F "options *" '/options/{print $2}' "${esp}/loader/entries/arch.conf" | \
        sed -e 's;intel_iommu=on;intel_iommu=off;' \
            -e 's;pcie_acs_override=downstream ;;' \
            -e 's;pci-stub.ids=10de:13c0,10de:0fbb ;;'
}

function run_kexec(){
    kernel_cmdline="$(cmdline) nvidia-drm.modeset=1 vga=0 rdblacklist=nouveau nouveau.modeset=0 rcutree.rcu_idle_gp_delay=1"
    echo "Do you want yo use: [${kernel_cmdline}] ?"
    read ans
    if [[ ${ans} == "y" ]]; then
        sudo kexec -l ${esp}/vmlinuz-${linux} --initrd=/boot/initramfs-${linux}.img --command-line="initrd=\\intel-ucode.img initrd=\\initramfs-${linux}.img ${kernel_cmdline}"
        sync
        sudo systemctl kexec
    fi
}

function update_config(){
    sudo mv -vi /etc/X11/xorg.conf{_bck,}
}

update_config
run_kexec "$@"
