#!/bin/zsh
setopt nullglob
typeit=0
[[ $1 == "--type" ]] && {typeit=1; shift}
[[ $(lpass status) = "Not logged in." ]] && lpass login serg.zorg@gmail.com

if [[ $(lpass ls) != "" ]]; then
    name=$(lpass ls | rofi -dmenu -p '[>>]')
    id=$(echo ${name} | sed -r 's/.*\id:\s([0-9]+).*/\1/g')
    if [[ ${typeit} -eq 0 ]]; then
        lpass show -c --password "${id}"
    else
        xdotool - <<<"type --clearmodifiers -- $(lpass show --password $id)"
    fi
fi
