#!/bin/zsh

image_="$1"

function conv_image_(){ 
    readonly size_=200
    [[ ! $1 =~ .*gif ]] && ~/bin/scripts/python_img_resizer.py ${size_} "$1" "$2"
}

function wf_(){
    builtin print "${st_}⟬${cl_}${bold_}$1${cl_}${st_}⟭${cl_} "
}

function send_notify_(){ 
    input=${image_}

    local st_=$(highlight 4)
    local st2_=$(highlight 200)
    local st3_=$(highlight 4)
    local bold_="<span weight='bold'>"

    local cl_="</span>"

    local header="⟬${input}⟭"
    header="$(sed -e "s:${HOME}:~:" \
                  -e "s:\/:${st_}/${cl_}:g" \
                  -e "s:\(⟬\|⟭\):${st3_}\1${cl_}:g" -e "s:~:${st2_}~${cl_}:g" <<< ${header})"

    local info_=$(/usr/bin/vendor_perl/exiftool -ImageSize -MIMEType -Megapixels ${image_})

    output=$(xargs -n4 <<< "${info_}" \
        | sed -e 's/^/⟬/' -e 's/$/⟭/' \
        -e "s;\(.*\):;${bold_}\\1${st3_}:${cl_}${cl_};" \
        -e "s:\(⟬\|⟭\):${st3_}\1${cl_}:g"
    )
    
    wait
    dunstify -h "string:fgcolor:$(xrq foreground)" -a "pic_notify" -i "${new_image}" "Making shot" "${header}\n${output}"
}

function highlight(){
    local msg="$(xrq color${1})"
    builtin print "<span weight='bold' color='${msg}'>"
}

function finish_(){
    (sleep 3s && rm -f "${new_image}") &
}

function main(){
    local shots_pikz="${HOME}/tmp/shots"
    [[ ! -d "${shots_pikz}" ]] && mkdir -p "${shots_pikz}"
    new_image="${HOME}/tmp/$(basename ${image_})_new.png"
    conv_image_ "${image_}" "${new_image}" &
    xclip <<< "${image_}"
    trap finish_ EXIT
    send_notify_ 
}

main "$@"
