#!/bin/zsh

scr_dir=~/tmp/shots
window='root'
name="screenshot"
filename="${name}-$(date +%Y-%m-%d_%H-%M-%S).png"
size_=200
colorspace_='0.96,0.5,0.09'
urgency_=normal
summary_="${scr_dir}/${filename}"

shot_notify(){
    ~/bin/scripts/pic_notify "${summary_}"
}

make_shot(){
    select_window_=false
    current_window_=false
    apply_colorpace_=false
    delay_min_=false
    delay_=false

    local -a arglist=()
    arglist+=( -p 0 )

    [[ ${select_window_} == true ]] && arglist+=( -s )
    [[ ${current_window_} == true ]] && arglist+=( -i $(xdotool getactivewindow) )
    [[ ${apply_colorpace_} == true ]] && arglist+=( -c "${colorspace_}" )
    [[ ${delay_min_} == true ]] && arglist+=( -d 0.5 )
    [[ ${delay_} == true ]] && arglist+=( -d 5 )

    arglist+="${summary_}"

    maim ${arglist[@]} && \
    shot_notify
}

[[ ! -d "${scr_dir}" ]] && mkdir "${scr_dir}"

select_(){ select_window_=true; make_shot "$@"; }
full_(){ make_shot "$@"; }
current_(){ delay_min_=true; current_window_=true; make_shot "$@"; }
delay_(){ delay_=true; make_shot "$@"; }

opts_=(
    "Full shot"
    "Rectangular selection shot"
    "Current window"
    "Delayed shot"
)

menu_(){
    local x11_width="$(xrandr -q |awk '/Screen/{print $8}')"
    local width_=$[x11_width-70]
    local lines_=10
    local yoffset_=-22

    readonly rofi_cmd=(
        rofi
        -theme-str "'#window { width:${width_}; y-offset: ${yoffset_}; location: south; anchor: south; }'"
        -theme-str "'#listview { lines:${lines_}; }'"
        -p "'[screen] >> '"
        -dmenu
    )
    case $(for opt in ${opts_}; do echo ${opt}; done | eval ${rofi_cmd[@]}) in
        [Rr]*) select_  "$@" ;;
        [Ff]*) full_    "$@" ;;
        [Cc]*) current_ "$@" ;;
        [Dd]*) delay_   "$@" ;;
    esac
}
 
case $1 in
    [Rr]*) select_  "$@" ;;
    [Cc]*) current_ "$@" ;;
    [Dd]*) delay_   "$@" ;;
    [Mm]*) menu_    "$@" ;;
    *)     full_    "$@" ;;
esac
