#!/bin/zsh
while true; do
    inotifywatch -r "${XDG_PICTURES_DIR}" 2> /dev/null
    find "${XDG_PICTURES_DIR}" -maxdepth 3 \
        -not -path "${XDG_PICTURES_DIR}/.git/*" \
        -not -path "${XDG_PICTURES_DIR}/.git" -type d -print0 \
        | _FASD_DATA="${XDG_DATA_HOME}/sxiv_do.data" xargs -0 fasd -A
done

make_human_readable(){ gawk -i inplace -F '|' '{print $1}' ${XDG_DATA_HOME}/sxiv_do.data }
