#!/bin/zsh
while resource="$(inotifywait -r  -e create "${XDG_PICTURES_DIR}"  --format %w%f . 2>/dev/null)"; do
    echo "${resource}" | _FASD_DATA="${XDG_DATA_HOME}/sxiv_do.data" xargs fasd -A
done

make_human_readable(){ gawk -i inplace -F '|' '{print $1}' ${XDG_DATA_HOME}/sxiv_do.data }
