#!/bin/bash

handle_all_devices(){
    USB_DEVICES+=("046d:c083" "046d:c32b" "05ac:12a8")
    # G403 Prodigy Gaming Mouse 
    # Logitech G910 [Keyboard]  
    # Apple, Inc. iPhone5/5C/5S/6/7

    # 1038:1702 # SteelSeries ApS [ Mouse ]
    # 046d:c32b # Logitech G910 [Keyboard]
    # 1e7d:2e22 # Roccat kone rtd [ Mouse ]
    # 1038:1702 # SteelSeries ApS [ Mouse ]
}

main(){
    # loop over given search strings
    for i in "${USB_DEVICES[@]}"; do
        # loop over results of search string
        (lsusb | grep -i "${i}") | while read line; do
            bus=$(echo "${line}" | cut -d" " -f2 | sed 's/^0*//')
            device=$(echo "${line}" | cut -d" " -f4 | sed 's/://' | sed 's/^0*//')
            vendor=$(echo "${line}" | cut -d" " -f6 | cut -d: -f1)
            product=$(echo "${line}" | cut -d" " -f6 | cut -d: -f2)
            guestbus="xhci.0"

            if hash jq 2> /dev/null; then
                bpasscmd(){
                    nc -q 3 localhost 4444 <<< "${1}" | jq -c 
                }
            else
                bpasscmd(){
                    nc -q 3 localhost 4444 <<< "${1}"  
                }
            fi

            if [[ ${1} == "add" ]]; then
                echo "Passing through (USB):"
                echo "${line}"
                cmd="
                { \"execute\": \"qmp_capabilities\" }
                { \"execute\": \"device_add\", \"arguments\": { \"driver\": \"usb-host\", \"hostbus\": \"${bus}\", \"hostaddr\": \"${device}\", \"id\": \"usb_${vendor}.${product}.${bus}.${device}\", \"bus\": \"${guestbus}\" }}
                "
                bpasscmd "${cmd}"
            elif [[ ${1} == "del" ]]; then
                echo "Undoing passthrough (USB):"
                echo ${line}
                cmd="
                { \"execute\": \"qmp_capabilities\" }
                { \"execute\": \"device_del\", \"arguments\": { \"id\": \"usb_$vendor.$product.$bus.$device\" }}
                "
                bpasscmd "${cmd}"
                sleep 0.5
            else
                echo "Unknown command $1! Use either add or del as first argument."
                kill -s TERM ${TOP_PID}
            fi
        done
    done
}


trap "exit 1" TERM
export TOP_PID=$$

USB_DEVICES=()

if [[ -z "$2" ]]; then
    handle_all_devices
else
    USB_DEVICES+=("$2")
fi

main "$@"

source "~neg/.zsh/00-common.zsh"
source "${XDG_CONFIG_HOME}/xinit/keyboard_and_mouse.zsh"
