#!/bin/zsh

do_if_qemu(){
    if pgrep qemu 2>/dev/null; then
        eval "$@"
    else
        no_qemu_msg
    fi
}

check_qemu(){
    local cmd=(sudo ~neg/bin/qemu/wrun)
    st dtach -c /tmp/qemu_wrun.session -Ez "${cmd[@]}"
}

msg(){ notify-send "$@" }
no_qemu_msg(){ msg "There is no QEMU" }

function main(){
    local -a opts_=(
        "[Usb :: passthrough add]"
        "[Usb :: passthrough del]"
        "[Start <Win10>]"
    )

    local width_=800
    local xoffset_=40
    local yoffset_=40

    local -a rofi_cmd=(
        rofi
        -theme-str "'#window { width:${width_}; x-offset: ${xoffset_}; y-offset: ${yoffset_}; location: north west; anchor: north west; }'"
        -i -p "'[vm] >> '" -dmenu
    )

    tmux -S ~/1st_level/vm.socket new -s vm

    case $(for opt in ${opts_}; do echo ${opt}; done | eval "${rofi_cmd[@]}") in
        *"Usb"*"pass"*"add"*) 
            do_if_qemu st tmux -S ~/1st_level/vm.socket new -n pass "${HOME}/bin/qemu/passthrough add"
        ;;
        *"Usb"*"pass"*"del"*) 
            do_if_qemu st tmux -S ~/1st_level/vm.socket new -n pass "${HOME}/bin/qemu/passthrough del"
            source ${XDG_CONFIG_HOME}/xinit/keyboard_and_mouse.zsh
        ;;
        *"Win"*"10"*)
            os_name=${res:s_Start__}
            msg "Starting ... ${os_name}"
            if ! check_qemu; then
                msg "Start ${os_name} failed" \
                    && exit 1
            else
                msg "Done"
            fi
        ;;
    esac
}

main "$@"
